### PR TITLE
PR for issue #38

### PR DESCRIPTION
**Pull request by thliebig**

### CODE REVIEW

**Comment by hgrecco** [comment]
Thanks a lot!

**Comment by thliebig** [comment]
@hgrecco How do you test use your development version of pyvisa-py? I had to run `python setup.py install` after every change to test it, otherwise pyvisa would always use the installed version of pyvisa-py only...

**Comment by hgrecco** [comment]
I have an isolated virtualenv with a symlink in to my development folder.

**Comment by MatthieuDartiailh** [comment]
You can use ```python setup.py develop```. When doing so only a link to your development folder is added to pythonpath.

**Pull request merged**
